$html = @"
<html>
<head><title>System Diagnostics Report</title></head>
<body>
<h1>System Report</h1>
<p>Generated by WinSysInsight</p>
</body>
</html>
"@

$html | Out-File -FilePath ./output/Report.html -Encoding UTF8
Write-Host "HTML report generated at ./output/Report.html"
